routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Auth;


Route::get('/logout', function () { Auth::logout(); Session::flush(); return redirect('/home'); });

Route::get('/test',function(){
    return view('Admin.dashboard');
});

Route::group(['middleware' => 'roles','roles' => ['Admin','User','Manager','automotive','private']], function () {
    
    Route::get('/profile/{id?}','App\Http\Controllers\HomeController@profile');
    Route::post('/profile-update','App\Http\Controllers\HomeController@profileUpdate');

    Route::get('/user-order/{status}', [App\Http\Controllers\Admin\AdminController::class, 'userOrder']);
    Route::get('/user-order-details/{id}', [App\Http\Controllers\Admin\AdminController::class, 'userOrderDetails']);

});

Route::group(['middleware' => 'CompleteProfile'], function(){

Route::group(['middleware' => 'roles','roles' => ['Admin','User','Manager','automotive','private']], function () {
    
    Route::post('/update-password','App\Http\Controllers\HomeController@updatePassword');
    Route::get('/car-register', 'App\Http\Controllers\CarRegisterController@index');
    Route::post('/car-register', 'App\Http\Controllers\CarRegisterController@carRegisterPost');
});

Route::group(['prefix' => 'automotive', 'roles' => 'automotive'], function () {
    Route::get('/dashboard',function(){
        return view('Admin.dashboard');
   });
});

Route::group(['prefix' => 'user', 'roles' => 'User'], function () {
    Route::get('/dashboard',function(){
        return view('Admin.dashboard');
   });
});

Route::group(['prefix' => 'private', 'roles' => 'private'], function () {
   Route::get('/dashboard',function(){
        return view('Admin.dashboard');
   });
});

Route::group(['middleware' => 'roles','roles' => 'Admin'], function() {

    Route::group(['prefix' => 'admin'],function(){
        Route::get('/dashboard', 'App\Http\Controllers\Admin\AdminController@dashboard');
        Route::resource('/coupon', 'App\Http\Controllers\Admin\CouponController')->name('*','coupon');
        Route::get('/orders', 'App\Http\Controllers\Admin\AdminController@orders');

        Route::get('/getSubCategory/{id}', [App\Http\Controllers\Admin\ProductController::class, 'getsubCategory']);
        Route::resource('/categories', 'App\Http\Controllers\Admin\CategoryController')->name('*','categories');
        Route::resource('/sub-categories', 'App\Http\Controllers\Admin\SubCategoryController')->name('*','sub-categories');
        Route::resource('/product', 'App\Http\Controllers\Admin\ProductController')->name('*','product');
        Route::resource('/coupon', 'App\Http\Controllers\Admin\CouponController')->name('*','coupon');
        Route::get('/order/{status}', [App\Http\Controllers\Admin\AdminController::class, 'userOrder']);
        Route::get('/order-details/{id}', [App\Http\Controllers\Admin\AdminController::class, 'userOrderDetails']);
        Route::get('/order-status-change/{id}/{val}','App\Http\Controllers\Admin\AdminController@orderStatusChange');
        

    });
    
    Route::resource('car-option', App\Http\Controllers\Admin\CarOptionController::class)->name('*', 'carOption');
    Route::resource('packages/automotive', App\Http\Controllers\Admin\PackagesController::class)->name('*', 'package');
    Route::resource('packages/private', App\Http\Controllers\Admin\PackagesController::class)->name('*', 'package');

});

Route::group(['prefix' => 'manager'], function() {

    Route::group(['middleware' => 'roles','roles' => 'Manager'],function(){
        Route::get('/dashboard','App\Http\Controllers\Admin\AdminController@dashboard');
    });

});

Route::group(['prefix' => 'user'], function() {

    Route::group(['middleware' => 'roles','roles' => 'User'],function(){
        Route::get('/user/dashboard','App\Http\Controllers\Admin\AdminController@dashboard');
    });

});


Route::group(['prefix' => '/'], function() {

    Route::get('/',function(){ 
        if(Auth::check()){
            if(Auth::user()->user_type == 'Admin'){ return redirect('/admin/dashboard'); }
            else{ return redirect('/home'); }
        }
        else{
            return redirect('/home');
        }
    });
    Route::get('/home','App\Http\Controllers\HomeController@index');
    Route::get('/package/{type}','App\Http\Controllers\HomeController@package');
    Route::get('/selling-profile','App\Http\Controllers\HomeController@sellingProfile');
    Route::get('/products', [App\Http\Controllers\HomeController::class, 'products'])->name('products');
    Route::get('/product/{id}', [App\Http\Controllers\HomeController::class, 'productDetails']);
    Route::resource('/cart', 'App\Http\Controllers\CartController')->name('*','cart');
    Route::get('/get-cart-count',function(){
        return response()->json(['cartCount' => session()->has('cart') ? count(session()->get('cart')) : 0]);
    });
    

    Route::group(['middleware' => 'guest'], function() {

        Route::get('/email-verified/{token}/{email}', [App\Http\Controllers\Auth\VerificationController::class, 'emailVerified'])->name('email-verification');

    });

    Route::group(['middleware' => 'auth'], function () {
        //Package checkout start here
        Route::get('/checkout/{id}','App\Http\Controllers\HomeController@checkoutPackage');
        Route::post('/checkout','App\Http\Controllers\HomeController@checkoutPost');
        //Package checkout end here

        //Ecommerce checkout start here
        Route::get('/product-checkout', [App\Http\Controllers\CartController::class, 'checkout'])->name('checkout');
        Route::post('/product-checkout', [App\Http\Controllers\CartController::class, 'checkoutStore'])->name('checkout-store');
        //Ecommerce checkout end here

        Route::get('/coupon-redeem/{val}/{id}',[App\Http\Controllers\HomeController::class, 'couponRedeem'])->name('couponRedeem');
        Route::get('/coupon-redeem/{val}',[App\Http\Controllers\HomeController::class, 'couponRedeemProduct'])->name('couponRedeemProduct');
    });

});


});

Auth::routes();
Route::get('/register/{type}','App\Http\Controllers\Auth\RegisterController@customRegister');

resources/views/Admin/categories.blade.php
@extends('layouts.admin')

@section('title') Categories @endsection

@section('header')

<link href="{{ asset('/dashboard/assets/plugins/custom/datatables/datatables.bundle.css?v=7.0.4') }}" rel="stylesheet" type="text/css" />

@endsection

@section('heading')
    @include('layouts.admin-heading',[ 'heading' => 'Categories', 'type' => 'option', 'btn' => 'Create Category'  ])
@endsection

@section('content')

<div class="section-body mt-3">
    <div class="container-fluid">

        <div class="row clearfix mt-2">

            <div class="col-lg-12" id="post" style="display:none">
                <div class="card card-custom gutter-b example example-compact">
                    <div class="card-header">
                        <h3 class="card-title">Category</h3>
                        <div class="card-toolbar">
                            <div class="example-tools justify-content-center">
                            <button type="button" class="btn btn-danger btn-sm" id="close"><span class="fa fa-times"></span></button>
                        </div>
                        </div>
                    </div>
                    <form id="formSubmit">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" name="name" id="name" class="form-control" placeholder="Category Name" />
                                    <small class="error_msg" id="name_msg"></small>
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Description</label>
                                    <textarea name="description" id="description" class="form-control" placeholder="Category Description"></textarea>
                                    <small class="error_msg" id="description_msg"></small>
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Image</label>
                                    <input type="file" name="image" id="image" class="form-control" accept="image/*" />
                                    <small class="error_msg" id="image_msg"></small>
                                </div>
                            </div>


                            <div class="col-md-6 imgDiv" style="display:none"><img href="" data-fancybox="images" class="fancy-box" id="img" style="width:100px; height:100px" /><input type="hidden" id="id" /></div>
                            <input type="hidden" name="type" value="product" />
                            <div class="col-md-6 imgDiv images" style="display:none"></div>

                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="col-md-12">
                            <button type="submit" id="btnSub" data-type="create" class="btn btn-primary mb-2" style="float:right">Submit</button>
                        </div>
                    </div>
                </form>
                </div>
            </div>

            <div class="col-lg-12" id="details">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="datatable" class="table table-hover js-basic-example table_custom border-style spacing5">
                                <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Name</th>
                                        <th>Description</th>
                                        <th>Date</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>                
        </div>
    </div>
</div>



@endsection

@section('footer')

<script src="{{ asset('/dashboard/assets/plugins/custom/datatables/datatables.bundle.js?v=7.0.4') }}"></script>
<script src="{{ asset('/dashboard/assets/js/pages/crud/datatables/advanced/column-visibility.js?v=7.0.4') }}"></script>
<script src="https://cdn.datatables.net/rowreorder/1.2.7/js/dataTables.rowReorder.min.js"></script>
<!-- <script src="https://cdn.datatables.net/rowreorder/1.2.7/js/dataTables.rowReorder.min.js"></script> -->
<script src="https://rawgit.com/notifyjs/notifyjs/master/dist/notify.js"></script>



<script>

$('#formSubmit').on('submit',function(e){
    e.preventDefault()
    $('.error_msg').html('')
    var btnSub = $("#btnSub").attr('data-type')
    const formData = new FormData(this)
    var url = btnSub == 'create' ? "{{route('categories.store')}}" : `{{url('/admin/categories')}}/${$('#id').val()}`
    btnSub == 'update' && formData.append('_method','PUT')
    $.ajaxSetup({
        headers:{'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
    })
    $.ajax({
        contentType: false,
        cache: false,
        processData: false,
        url: url,
        method: 'POST',
        data: formData,
        beforeSend:function(){
            $("#btnSub").prop("disabled", true);
        },
        success:function(res){
            if(res.msg == 'success'){
                $.notify(res.res, { globalPosition:"top center", autoHideDelay: 5000, className:'success' });
                close()
                $('#btnSub').attr('data-type','create')
                getData()
            }
            else{
                $.notify(res.res, { globalPosition:"top center", autoHideDelay: 5000, className:'error' });
                $('#btnSub').attr('data-type','create')
            }
            $("#btnSub").prop("disabled", false);
        },
        error:function(error){
            $.each(error.responseJSON.errors,function(key,value) {
                $("#"+key+"_msg").html(value);
            });
                $("#btnSub").prop("disabled", false);
        },
    })

})




$(document).on('click','.edit',function(){
    $('.error_msg').html('')
    var id = $(this).attr('data-id')
    $.ajax({
        url:`{{url('/admin/categories')}}/${id}/edit`,
        type:"GET",
        success:function(res){
            if(res.msg == 'success'){
                var html = ''
                $('#name').val(res.post.name)
                $('#id').val(res.post.id)
                $('#description').val(res.post.description)
                $('#img').attr('src',res.post.image)
                $('#img').attr('href',res.post.image)
                $('#btnSub').attr('data-type','update')
                $('.imgDiv').css('display','block')
                $('.title').html('Update Category')
                open()
                window.scrollTo({ top: 100, left: 100, behavior: 'smooth' });
            }
            else{
                $.notify('Unable to fetch record.', { globalPosition:"top center", autoHideDelay: 5000, className:'error' });
            }
        }
    })
})


$(document).on('click','.delImage',function(){
    var id = $(this).attr('data-id')
    $.ajax({
        url:`{{url('/admin/categories/create')}}?id=${id}`,
        type:"GET",
        success:function(res){
            if(res == '1'){
                $('#'+id).remove()
            }
        }
    })
})


$(document).on('click','.delete',function(){
    var id = $(this).attr('data-id')
    Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
    }).then((result) => {
        if (result.value) {
        $.ajaxSetup({
            headers:{'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
        })
        $.ajax({
            url:`{{url('admin/categories')}}/${id}`,
            type:"DELETE",
            success:function(res){
                if(res.msg == 'success'){
                    $.notify(res.res, { globalPosition:"top center", autoHideDelay: 5000, className:'success' });
                    getData()
                }
                else{
                    $.notify('Error while deleting event', { globalPosition:"top center", autoHideDelay: 5000, className:'error' });
                }
            }
        })

        }
    })

})

getData()

function getData(){
    $('#datatable').DataTable().destroy();
        var userTable = $('#datatable').DataTable({
          processing: true,
          serverSide: true,
          responsive: false,
          language: {
              search: "",
              searchPlaceholder: "Search records"
         },
          ajax:{
              url: "{{ route('categories.index') }}"
           },
          columns: [
            { data: 'image', name: 'image', orderable: false },
            { data: 'name', name: 'name' },
            { data: 'description', name: 'description' },
            { data: 'date', name: 'date' },
            { data: 'action', name: 'action', orderable: false },
        ]

    });
}

$(document).on('click','.showMore',function(){
    let id = $(this).attr('data-id')
    let type = $(this).attr('data-type')
    let less = $(this).attr('data-less')
    let more = $(this).attr('data-content')
    if(type == 'less'){
        $(`#${id}`).attr('data-type','more')
        $(`#content${id}`).html(more)
        $(`#${id}`).html('[See Less]')
    }
    else if(type == 'more'){
        $(`#${id}`).attr('data-type','less')
        $(`#content${id}`).html(less)
        $(`#${id}`).html('[See More]')
    }
})

</script>
    
@endsection

resources/views/Admin/coupon.blade.php
@extends('layouts.admin')

@section('title') Coupon @endsection

@section('header')

<link href="{{ asset('/dashboard/assets/plugins/custom/datatables/datatables.bundle.css?v=7.0.4') }}" rel="stylesheet" type="text/css" />

@endsection

@section('heading')
    @include('layouts.admin-heading',[ 'heading' => 'Coupon', 'type' => 'packages', 'btn' => 'Create Coupon'  ])
@endsection

@section('content')


<!--begin::Card-->
<div class="card card-custom gutter-b example example-compact" id="post" style="display:none">
    <div class="card-header">
        <h3 class="card-title">Coupon</h3>
        <div class="card-toolbar">
            <div class="example-tools justify-content-center">
                <button type="button" class="btn btn-danger btn-sm" id="close">
                    <span class="fa fa-times"></span>
                </button>
            </div>
        </div>
    </div>
    <!--begin::Form-->
    <form id="formSubmit">
        <div class="card-body">
            <div class="row">

            <div class="col-md-6">
                <div class="form-group">
                    <label>Title</label>
                    <input type="text" name="title" id="title" class="form-control" placeholder="Coupon Title" />
                    <span class="form-text text-muted error_msg" id="title_msg"></span>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label>Expiry Date</label>
                    <input type="date" name="expiry_date" id="expiry_date" class="form-control" />
                    <span class="form-text text-muted error_msg" id="expiry_date_msg"></span>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label>Coupon Type</label>
                    <select name="coupon_type" id="coupon_type" class="form-control">
                        <option value="0" selected hidden>Select Coupon Type</option>
                        <option value="Percent">Percent</option>
                        <option value="Amount">Amount</option>
                    </select>
                    <span class="form-text text-muted error_msg" id="coupon_type_msg"></span>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label>Value</label>
                    <input type="number" step="any" name="value" id="value" class="form-control" placeholder="Discount Value e.g. 10"/>
                    <span class="form-text text-muted error_msg" id="value_msg"></span>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <label>Coupon Code</label>
                    <input type="text" name="code" id="code" class="form-control" placeholder="AC123"/>
                    <span class="form-text text-muted error_msg" id="code_msg"></span>
                </div>
            </div>

            <div class="col-md-6 imgDiv" style="display:none"><img href="" data-fancybox="images" class="fancy-box" id="img" style="width:100px; height:100px" /><input type="hidden" id="id" /></div>

            <div class="col-md-6 imgDiv images" style="display:none"></div>
            <input type="hidden" value="product" name="product" />
            <input type="hidden" name="type" value="product" />
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary mb-2" id="btnSub" data-type="create" style="float:right">Submit</button>
        </div>
    </form>
    <!--end::Form-->
</div>
<!--end::Card-->



<!--begin::Card-->
<div class="card card-custom" id="details">
    <div class="card-header">
        <div class="card-title">
            <h3 class="card-label" style="text-transform:capitalize">Manage Coupons</h3>
        </div>
        <div class="card-toolbar">
            <!--begin::Dropdown-->
            <div class="dropdown dropdown-inline mr-2">

            </div>
            <!--end::Dropdown-->
        </div>
    </div>
    <div class="card-body">
        <!--begin: Datatable-->
        <table class="table table-bordered table-hover table-checkable" id="datatable" style="margin-top: 13px !important">
            <thead>
                <tr>
                    <!-- <th>Order</th> -->
                    <th>Title</th>
                    <th>Expiry Date</th>
                    <th>Code</th>
                    <th>Type</th>
                    <th>Value</th>
                    <th>Action</th>
                </tr>
            </thead>
        </table>
        <!--end: Datatable-->
    </div>
</div>
<!--end::Card-->



@endsection

@section('footer')

<script src="{{ asset('/dashboard/assets/plugins/custom/datatables/datatables.bundle.js?v=7.0.4') }}"></script>
<script src="{{ asset('/dashboard/assets/js/pages/crud/datatables/advanced/column-visibility.js?v=7.0.4') }}"></script>
<script src="https://cdn.datatables.net/rowreorder/1.2.7/js/dataTables.rowReorder.min.js"></script>
<!-- <script src="https://cdn.datatables.net/rowreorder/1.2.7/js/dataTables.rowReorder.min.js"></script> -->
<script src="https://rawgit.com/notifyjs/notifyjs/master/dist/notify.js"></script>
<script>

$('#formSubmit').on('submit',function(e){
    e.preventDefault()
    $('.error_msg').html('')
    var btnSub = $("#btnSub").attr('data-type')
    const formData = new FormData(this)
    var url = btnSub == 'create' ? "{{route('coupon.store')}}" : `{{url('/admin/coupon')}}/${$('#id').val()}`
    btnSub == 'update' && formData.append('_method','PUT')
    $.ajaxSetup({
        headers:{'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
    })
    $.ajax({
        contentType: false,
        cache: false,
        processData: false,
        url: url,
        method: 'POST',
        data: formData,
        beforeSend:function(){
            $("#btnSub").prop("disabled", true);
        },
        success:function(res){
            if(res.msg == 'success'){
                $.notify(res.res, { globalPosition:"top center", autoHideDelay: 5000, className:'success' });
                close()
                $('#btnSub').attr('data-type','create')
                getData()
            }
            else{
                $.notify(res.res, { globalPosition:"top center", autoHideDelay: 5000, className:'error' });
                $('#btnSub').attr('data-type','create')
            }
            $("#btnSub").prop("disabled", false);
        },
        error:function(error){
            $.each(error.responseJSON.errors,function(key,value) {
                $("#"+key+"_msg").html(value);
            });
                $("#btnSub").prop("disabled", false);
        },
    })

})




$(document).on('click','.edit',function(){
    $('.error_msg').html('')
    var id = $(this).attr('data-id')
    $.ajax({
        url:`{{url('/admin/coupon')}}/${id}/edit`,
        type:"GET",
        success:function(res){
            if(res.msg == 'success'){
                var html = ''
                $('#title').val(res.post.title)
                $('#code').val(res.post.code)
                $('#id').val(res.post.id)
                $('#value').val(res.post.value)
                $('#expiry_date').val(res.post.expiry_date)
                $(`#coupon_type option[value=${res.post.coupon_type}]`).attr('selected','selected')
                $('#btnSub').attr('data-type','update')
                $('.title-head').html('Update Coupon')
                open()
            }
            else{
                $.notify('Unable to fetch record.', { globalPosition:"top center", autoHideDelay: 5000, className:'error' });
            }
        }
    })
})



$(document).on('click','.delete',function(){
    var id = $(this).attr('data-id')
    Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
    }).then((result) => {
        if (result.value) {
        $.ajaxSetup({
            headers:{'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
        })
        $.ajax({
            url:`{{url('admin/coupon')}}/${id}`,
            type:"DELETE",
            success:function(res){
                if(res.msg == 'success'){
                    $.notify(res.res, { globalPosition:"top center", autoHideDelay: 5000, className:'success' });
                    getData()
                }
                else{
                    $.notify('Error while deleting event', { globalPosition:"top center", autoHideDelay: 5000, className:'error' });
                }
            }
        })

        }
    })

})

getData()

function getData(){
    $('#datatable').DataTable().destroy();
        var userTable = $('#datatable').DataTable({
          processing: true,
          serverSide: true,
          responsive: false,
          language: {
              search: "",
              searchPlaceholder: "Search records"
         },
          ajax:{
              url: "{{ route('coupon.index') }}"
           },
          columns: [
            { data: 'title', name: 'title' },
            { data: 'expire', name: 'expire' },
            { data: 'code', name: 'code' },
            { data: 'type', name: 'type' },
            { data: 'value', name: 'value' },
            { data: 'action', name: 'action', orderable: false },
        ]

    });
}

</script>

@endsection

resources/views/Admin/example-dashboard.blade.php
@extends('layouts.admin')

@section('title') Packages @endsection

@section('header')

<link href="{{ asset('/dashboard/assets/plugins/custom/datatables/datatables.bundle.css?v=7.0.4') }}" rel="stylesheet" type="text/css" />

@endsection

@section('heading')
    @include('layouts.admin-heading',[ 'heading' => Request::segment(2).' Packages', 'type' => 'packages', 'btn' => 'Create Package'  ])
@endsection

@section('content')


<!--begin::Card-->
<div class="card card-custom gutter-b example example-compact" id="post" style="display:none">
    <div class="card-header">
        <h3 class="card-title">Package</h3>
        <div class="card-toolbar">
            <div class="example-tools justify-content-center">
                <button type="button" class="btn btn-danger btn-sm" id="close">
                    <span class="fa fa-times"></span>
                </button>
            </div>
        </div>
    </div>
    <!--begin::Form-->
    <form id="formSubmit">
        <div class="card-body">
            <div class="row">

                <div class="col-md-6">
                    <div class="form-group">
                        <label>Email address</label>
                        <input type="text" class="form-control" placeholder="" name="" id="" />
                        <span class="form-text text-muted error_msg"></span>
                    </div>
                </div>

                <div class="col-md-6 imgDiv" style="display:none"><img href="" data-fancybox="images" class="fancy-box" id="img" style="width:100px; height:100px" /><input type="hidden" id="id" /></div>

                <div class="col-md-6 imgDiv images" style="display:none"></div>

            </div>

        </div>
        <div class="card-footer">
            <button type="reset" class="btn btn-primary mb-2" id="btnSub" data-type="create" style="float:right">Submit</button>
        </div>
    </form>
    <!--end::Form-->
</div>
<!--end::Card-->



<!--begin::Card-->
<div class="card card-custom" id="details">
    <div class="card-header">
        <div class="card-title">
            <h3 class="card-label" style="text-transform:capitalize">Manage {{ Request::segment(2) }} Packages</h3>
        </div>
        <div class="card-toolbar">
            <!--begin::Dropdown-->
            <div class="dropdown dropdown-inline mr-2">

            </div>
            <!--end::Dropdown-->
        </div>
    </div>
    <div class="card-body">
        <!--begin: Datatable-->
        <table class="table table-bordered table-hover table-checkable" id="datatable" style="margin-top: 13px !important">
            <thead>
                <tr>
                    <th>Record ID</th>
                    <th>Order ID</th>
                    <th>Country</th>
                    <th>Ship City</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>64616-103</td>
                    <td>Brazil</td>
                    <td>São Félix do Xingu</td>
                </tr>
                
            </tbody>
        </table>
        <!--end: Datatable-->
    </div>
</div>
<!--end::Card-->



@endsection

@section('footer')

<script src="{{ asset('/dashboard/assets/plugins/custom/datatables/datatables.bundle.js?v=7.0.4') }}"></script>
<script src="{{ asset('/dashboard/assets/js/pages/crud/datatables/advanced/column-visibility.js?v=7.0.4') }}"></script>
<script src="https://rawgit.com/notifyjs/notifyjs/master/dist/notify.js"></script>
<script src="{{ asset('/script/packages.js') }}"></script>

@endsection

resources/views/Admin/orders.blade.php
@extends('layouts.admin')

@section('title') Packages @endsection

@section('header')

<link href="{{ asset('/dashboard/assets/plugins/custom/datatables/datatables.bundle.css?v=7.0.4') }}" rel="stylesheet" type="text/css" />

@endsection

@section('heading')
    @include('layouts.admin-heading',[ 'heading' => 'Purchased Packages', 'type' => null ])
@endsection

@section('content')

<!--begin::Card-->
<div class="card card-custom" id="details">
    <div class="card-header">
        <div class="card-title">
            <h3 class="card-label" style="text-transform:capitalize">Manage Orders</h3>
        </div>
        <div class="card-toolbar">
        <select class="form-control" id="filter">
                    <option value="0" selected hidden>Select Purchased Type</option>
                    <option value="1">All</option>
                    <option value="automotive">Automotive Package</option>
                    <option value="private">Private Seller</option>
                </select>
        </div>
    </div>
    <div class="card-body">
        <!--begin: Datatable-->
        <table class="table table-bordered table-hover table-checkable" id="datatable" style="margin-top: 13px !important">
            <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Address</th>
                    <th>Amount Payed</th>
                    <th>Package</th>
                </tr>
            </thead>
        </table>
        <!--end: Datatable-->
    </div>
</div>
<!--end::Card-->



@endsection

@section('footer')
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
<!-- <script src="{{ asset('/dashboard/assets/plugins/custom/datatables/datatables.bundle.js?v=7.0.4') }}"></script>-->
<script src="https://rawgit.com/notifyjs/notifyjs/master/dist/notify.js"></script>
<script src="{{ asset('/script/order.js') }}"></script>

@endsection